# Generated by Django 5.0.7 on 2024-11-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0003_remove_customer_email_remove_customer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
    ]
