# Generated by Django 5.0.7 on 2024-11-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
